<?php

namespace Tests\Feature\Product;

use Illuminate\Testing\Fluent\AssertableJson;
use Tests\TestCase;

class ProductTest extends TestCase
{
    private string $baseUrl;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->baseUrl = '/api';
    }

    public function testIfAllProductsCanBeGotten(): void
    {
        $url = $this->baseUrl . "/products";
        $this->get($url)
            ->assertJson(fn(AssertableJson $json) =>
            $json
                ->where('success', true)
                ->where('message', trans('general.fetch'))
                ->has('data.0', fn($json) =>
                $json
                    ->has('name')
                    ->has('price')
                    ->etc())->etc());
    }
}
